version: "2.4"
services:
  vroom:
    network_mode: host
    image: vroomvrp/vroom-docker:v1.10.0
    container_name: vroom
    volumes:
      - ./vroom-conf/:/conf
    environment:
      - VROOM_ROUTER=osrm  # router to use, osrm, valhalla or ors
    depends_on:
      - osrm

  # EXAMPLE for OSRM, please consult the repo for details: https://hub.docker.com/r/osrm/osrm-backend/
  osrm:
    image: osrm/osrm-backend
    container_name: osrm
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./osrm:/data
    command: "osrm-routed --max-matching-size 1000 --max-table-size 1000 --max-viaroute-size 1000 --algorithm mld /data/map.osrm"

  # EXAMPLE for Valhalla, please consult the repo for details: https://github.com/gis-ops/docker-valhalla
#  valhalla:
#    image: gisops/valhalla:latest
#    container_name: valhalla_latest
#    ports:
#      - 8002:8002
#    volumes:
#      - ./custom_files/:/custom_files
#    environment:
#      # Auto-download PBFs from Geofabrik
#      #- tile_urls=https://download.geofabrik.de/europe/andorra-latest.osm.pbf https://download.geofabrik.de/europe/albania-latest.osm.pbf
#      # Get correct bounding box from e.g. https://boundingbox.klokantech.com/
#      #- min_x=18 # -> Albania | -180 -> World
#      #- min_y=38 # -> Albania | -90  -> World
#      #- max_x=22 # -> Albania |  180 -> World
#      #- max_y=43 # -> Albania |  90  -> World
#      - server_threads=2  # determines how many threads will be used to run valhalla
#      - use_tiles_ignore_pbf=True  # load existing valhalla_tiles.tar directly
#      - build_elevation=False  # build elevation with "True" or "Force", needs valid coordinates min_x, min_y etc
#      - build_admins=False  # build admins db with "True" or "Force"
#      - build_time_zones=False  # build timezone db with "True" or "Force"
#      - force_rebuild=False  # forces a rebuild of the routing tiles with "True"

  # EXAMPLE for OpenRouteService, please consult the repo for details: https://github.com/GIScience/openrouteservice
#  ors:
#    container_name: ors
#    ports:
#      - 8080:8080
#    image: openrouteservice/openrouteservice:latest
#    volumes:
#      - ./graphs:/ors-core/data/graphs
#      - ./elevation_cache:/ors-core/data/elevation_cache
#      - ./logs/ors:/var/log/ors
#      - ./logs/tomcat:/usr/local/tomcat/logs
#      - ./conf:/ors-conf
#      - ./path/to/pbf:/ors-core/data/osm_file.pbf  # alter path to your local OSM PBF file, e.g. from https://download.geofabrik.de
#    environment:
#      - BUILD_GRAPHS=False  # Forces the container to rebuild the graphs, e.g. when PBF is changed in app.config
#      - "JAVA_OPTS=-Djava.awt.headless=true -server -XX:TargetSurvivorRatio=75 -XX:SurvivorRatio=64 -XX:MaxTenuringThreshold=3 -XX:+UseG1GC -XX:+ScavengeBeforeFullGC -XX:ParallelGCThreads=4 -Xms1g -Xmx2g"
#      - "CATALINA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9001 -Dcom.sun.management.jmxremote.rmi.port=9001 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost"
